"""Fix messages updated_at

Revision ID: 0345f6366ac4
Revises: 851cb5e34733
Create Date: 2026-09-21 19:18:58.508744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0345f6366ac4'
down_revision: Union[str, Sequence[str], None] = '851cb5e34733'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('prompt_content', sa.String(), nullable=False),
    sa.Column('response_content', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'STREAMING', 'FAILED', 'CANCELLED', 'COMPLETED', name='messagestatus'), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('response_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('input_cost', sa.Numeric(), nullable=True),
    sa.Column('output_cost', sa.Numeric(), nullable=True),
    sa.Column('total_cost', sa.Numeric(), nullable=True),
    sa.Column('ttft', sa.Float(), nullable=True),
    sa.Column('total_time', sa.Float(), nullable=True),
    sa.Column('is_success', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
